#!/bin/sh
set -e
# Bundle worker.ts with esbuild, then deploy from a temp dir to avoid wrangler
# picking up wrangler.jsonc (generated by adapter-cloudflare for Pages).
root=$(pwd)
./node_modules/.bin/esbuild worker.ts \
  --bundle \
  --format=esm \
  --platform=browser \
  --target=esnext \
  --outfile=_worker_bundle.js
tmp=$(mktemp -d)
cp _worker_bundle.js "$tmp/worker.js"
cp wrangler.toml "$tmp/"
cd "$tmp" && wrangler deploy
rm -rf "$tmp"
rm -f "$root/_worker_bundle.js"
